version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URL: mongodb://mongo:27017/ecommerce
      RAZORPAY_KEY: your_key
      RAZORPAY_SECRET: your_secret
    depends_on:
      - mongo
    networks:
      - ecommerce-net

  mongo:
    image: mongo
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-net

networks:
  ecommerce-net:

volumes:
  mongo_data:

