services:
  frontend:
    image: localhost:5000/ecommerce-frontend:latest
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - ecommerce-net

  backend:
    image: localhost:5000/ecommerce-backend:latest
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URL: mongodb://mongo:27017/ecommerce
      RAZORPAY_KEY: your_key
      RAZORPAY_SECRET: your_secret
    depends_on:
      - mongo
    restart: always
    networks:
      - ecommerce-net

  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - ecommerce-net

networks:
  ecommerce-net:

volumes:
  mongo_data:

