name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: docker build -t localhost:5000/ecommerce-frontend:latest ./client

      - name: Build Backend
        run: docker build -t localhost:5000/ecommerce-backend:latest ./server

      - name: Push Images
        run: |
          docker push localhost:5000/ecommerce-frontend:latest
          docker push localhost:5000/ecommerce-backend:latest

      - name: Restart Containers
        run: |
          docker compose down
          docker compose up -d
