name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Image Tag
        run: |
          echo "TAG=$(date +'%d%m%y')" >> $GITHUB_ENV

      - name: Build Frontend
        run: |
          docker build -t localhost:5000/ecommerce-frontend:${{ env.TAG }} ./client

      - name: Build Backend
        run: |
          docker build -t localhost:5000/ecommerce-backend:${{ env.TAG }} ./server

      - name: Push Images
        run: |
          docker push localhost:5000/ecommerce-frontend:${{ env.TAG }}
          docker push localhost:5000/ecommerce-backend:${{ env.TAG }}

      - name: Wait
        run: sleep 20

      - name: Deploy
        run: |
          export TAG=${{ env.TAG }}
          docker compose down
          docker compose up -d

      - name: Wait for Containers
        run: sleep 30

      - name: Verify Containers
        run: docker ps
